'useclient'
import{useEffect,useState}from'react'
import{createClient}from'@/lib/supabase'
import{useRouter}from'next/navigation'
importLinkfrom'next/link'
import{ChevronLeft,Plus,Check,X,Settings,Users,Trophy,Calendar}from'lucide-react'
import{format}from'date-fns'
import{useLang}from'../LanguageContext'

typeAdminTab='tournaments'|'members'|'matches'|'results'

exportdefaultfunctionAdminPage(){
const{t}=useLang()
constrouter=useRouter()
const[user,setUser]=useState<any>(null)
const[profile,setProfile]=useState<any>(null)
const[tab,setTab]=useState<AdminTab>('tournaments')
const[tournaments,setTournaments]=useState<any[]>([])
const[selectedTournament,setSelectedTournament]=useState<string>('')
const[pendingMembers,setPendingMembers]=useState<any[]>([])
const[allMembers,setAllMembers]=useState<any[]>([])
const[matches,setMatches]=useState<any[]>([])
const[loading,setLoading]=useState(true)
constsupabase=createClient()

useEffect(()=>{init()},[])
useEffect(()=>{if(selectedTournament)loadTournamentData()},[selectedTournament])

asyncfunctioninit(){
const{data:{user}}=awaitsupabase.auth.getUser()
if(!user){router.push('/auth');return}
const{data:prof}=awaitsupabase.from('profiles').select('*').eq('id',user.id).single()
if(!prof?.is_super_admin){router.push('/');return}
setUser(user);setProfile(prof)
const{data:tours}=awaitsupabase.from('tournaments').select('*').order('created_at',{ascending:false})
setTournaments(tours||[])
if(tours?.length)setSelectedTournament(tours[0].id)
setLoading(false)
}

asyncfunctionloadTournamentData(){
const[membRes,matchRes,profilesRes]=awaitPromise.all([
supabase.from('tournament_members').select('*').eq('tournament_id',selectedTournament).order('joined_at'),
supabase.from('matches').select('*').eq('tournament_id',selectedTournament).order('kickoff_at'),
supabase.from('profiles').select('id,display_name,email'),
])
constprofiles=profilesRes.data||[]
constmembers=(membRes.data||[]).map((m:any)=>({
...m,
profiles:profiles.find((p:any)=>p.id===m.user_id)
}))
setPendingMembers(members.filter((m:any)=>m.status==='pending'))
setAllMembers(members)
setMatches(matchRes.data||[])
}

asyncfunctionapproveMember(memberId:string,approve:boolean){
awaitsupabase.from('tournament_members').update({
status:approve?'approved':'rejected',
approved_by:user.id,
approved_at:newDate().toISOString()
}).eq('id',memberId)
loadTournamentData()
}

asyncfunctionsaveResult(matchId:string,homeScore:number,awayScore:number){
awaitsupabase.from('matches').update({home_score:homeScore,away_score:awayScore}).eq('id',matchId)
loadTournamentData()
}

asyncfunctiongoLive(matchId:string){
awaitsupabase.from('matches').update({status:'live',home_score:0,away_score:0,result_locked:false}).eq('id',matchId)
loadTournamentData()
}

asyncfunctionupdateLiveScore(matchId:string,homeScore:number,awayScore:number){
//Setscoresfirst,thencalcpoints(functiononlyneedshome_scorenotnull)
awaitsupabase.from('matches').update({home_score:homeScore,away_score:awayScore,status:'completed'}).eq('id',matchId)
awaitsupabase.rpc('calculate_match_points',{p_match_id:matchId})
//Revertstatusbacktolive
awaitsupabase.from('matches').update({status:'live'}).eq('id',matchId)
loadTournamentData()
}

asyncfunctionendLive(matchId:string,homeScore:number,awayScore:number){
awaitsupabase.from('matches').update({home_score:homeScore,away_score:awayScore,status:'completed',result_locked:true}).eq('id',matchId)
awaitsupabase.rpc('calculate_match_points',{p_match_id:matchId})
loadTournamentData()
}

asyncfunctionlockResult(matchId:string,homeScore:number,awayScore:number){
awaitsupabase.from('matches').update({home_score:homeScore,away_score:awayScore,status:'completed',result_locked:true}).eq('id',matchId)
awaitsupabase.rpc('calculate_match_points',{p_match_id:matchId})
loadTournamentData()
}

asyncfunctionenterResult(matchId:string,homeScore:number,awayScore:number){
awaitsupabase.from('matches').update({home_score:homeScore,away_score:awayScore,status:'completed'}).eq('id',matchId)
awaitsupabase.rpc('calculate_match_points',{p_match_id:matchId})
loadTournamentData()
}

if(loading)return<divclassName="min-h-screenflexitems-centerjustify-center"><divstyle={{fontFamily:'var(--font-display)',color:'var(--green-light)',letterSpacing:'0.1em'}}>LOADING...</div></div>

constcurrentTournament=tournaments.find((t:any)=>t.id===selectedTournament)

return(
<divclassName="min-h-screen">
<headerstyle={{borderBottom:'1pxsolidvar(--dark-border)',background:'rgba(10,15,13,0.9)',backdropFilter:'blur(12px)',position:'sticky',top:0,zIndex:50}}>
<divclassName="max-w-5xlmx-autopx-4py-3flexitems-centergap-3">
<Linkhref="/"style={{color:'rgba(255,255,255,0.4)',display:'flex',alignItems:'center'}}><ChevronLeftsize={18}/></Link>
<spanstyle={{fontFamily:'var(--font-display)',fontSize:'1.1rem',letterSpacing:'0.08em',flex:1}}>ADMINPANEL</span>
<spanstyle={{fontSize:'0.8rem',color:'rgba(255,255,255,0.35)'}}>{profile?.display_name}</span>
</div>
</header>

<divclassName="max-w-5xlmx-autopx-4pt-6pb-16">
{/*Tournamentselector*/}
<divstyle={{display:'flex',alignItems:'center',gap:'1rem',marginBottom:'1.5rem',flexWrap:'wrap'}}>
<selectvalue={selectedTournament}onChange={e=>setSelectedTournament(e.target.value)}className="input"style={{maxWidth:280}}>
{tournaments.map((t:any)=><optionkey={t.id}value={t.id}>{t.name}</option>)}
</select>
{pendingMembers.length>0&&(
<spanclassName="badgebadge-red">{pendingMembers.length}pendingapproval</span>
)}
</div>

{/*Tabs*/}
<divclassName="tab-nav"style={{marginBottom:'1.5rem'}}>
<buttonclassName={`tab-btn${tab==='tournaments'?'active':''}`}onClick={()=>setTab('tournaments')}><Settingssize={13}style={{display:'inline',marginRight:4}}/>Setup</button>
<buttonclassName={`tab-btn${tab==='members'?'active':''}`}onClick={()=>setTab('members')}><Userssize={13}style={{display:'inline',marginRight:4}}/>Members{pendingMembers.length>0&&`(${pendingMembers.length})`}</button>
<buttonclassName={`tab-btn${tab==='matches'?'active':''}`}onClick={()=>setTab('matches')}><Calendarsize={13}style={{display:'inline',marginRight:4}}/>Matches</button>
<buttonclassName={`tab-btn${tab==='results'?'active':''}`}onClick={()=>setTab('results')}><Trophysize={13}style={{display:'inline',marginRight:4}}/>Results</button>
</div>

{/*TournamentSetup*/}
{tab==='tournaments'&&(
<TournamentSetuptournament={currentTournament}onSave={init}onCreate={init}supabase={supabase}/>
{currentTournament?.invite_code&&(
<divclassName="card"style={{padding:'1.25rem',marginTop:'1rem'}}>
<divstyle={{fontSize:'0.75rem',color:'rgba(255,255,255,0.4)',marginBottom:'0.5rem',fontWeight:600,letterSpacing:'0.06em'}}>📨INVITELINK</div>
<divstyle={{display:'flex',alignItems:'center',gap:'0.75rem',flexWrap:'wrap'}}>
<codestyle={{flex:1,fontSize:'0.78rem',color:'#4ade80',background:'rgba(74,222,128,0.08)',padding:'0.5rem0.75rem',borderRadius:8,wordBreak:'break-all'}}>
{typeofwindow!=='undefined'?`${window.location.origin}/join/${currentTournament.invite_code}`:`/join/${currentTournament.invite_code}`}
</code>
<buttonclassName="btnbtn-primary"style={{padding:'0.5rem0.9rem',fontSize:'0.8rem',flexShrink:0}}
onClick={()=>{consturl=`${window.location.origin}/join/${currentTournament.invite_code}`;navigator.clipboard.writeText(url).then(()=>alert('Invitelinkcopied!ShareitonWhatsApp🎉'))}}>
Copylink
</button>
</div>
<pstyle={{fontSize:'0.72rem',color:'rgba(255,255,255,0.25)',marginTop:'0.5rem'}}>
Linkexpiresoncethefirstmatchresultisentered.
</p>
</div>
)}
)}

{/*Members*/}
{tab==='members'&&(
<divstyle={{display:'flex',flexDirection:'column',gap:'1.5rem'}}>
{pendingMembers.length>0&&(
<div>
<h3style={{fontFamily:'var(--font-display)',fontSize:'1rem',letterSpacing:'0.08em',color:'#f87171',marginBottom:'0.75rem'}}>PENDINGAPPROVAL</h3>
<divstyle={{display:'flex',flexDirection:'column',gap:'0.5rem'}}>
{pendingMembers.map((m:any)=>(
<divkey={m.id}className="card"style={{padding:'1rem1.25rem',display:'flex',alignItems:'center',gap:'1rem'}}>
<divstyle={{flex:1}}>
<divstyle={{fontWeight:500}}>{m.profiles?.display_name}</div>
<divstyle={{fontSize:'0.8rem',color:'rgba(255,255,255,0.35)'}}>{m.profiles?.email}·Requested{format(newDate(m.joined_at),'dMMMyyyy')}</div>
</div>
<buttononClick={()=>approveMember(m.id,true)}className="btnbtn-primary"style={{padding:'0.45rem0.9rem',fontSize:'0.8rem'}}>
<Checksize={13}/>Approve
</button>
<buttononClick={()=>approveMember(m.id,false)}className="btnbtn-danger"style={{padding:'0.45rem0.9rem',fontSize:'0.8rem'}}>
<Xsize={13}/>Reject
</button>
</div>
))}
</div>
</div>
)}
<div>
<h3style={{fontFamily:'var(--font-display)',fontSize:'1rem',letterSpacing:'0.08em',color:'rgba(255,255,255,0.5)',marginBottom:'0.75rem'}}>ALLMEMBERS({allMembers.length})</h3>
<divclassName="card"style={{overflow:'hidden'}}>
{allMembers.map((m:any,i:number)=>(
<divkey={m.id}style={{display:'flex',alignItems:'center',gap:'1rem',padding:'0.875rem1.25rem',borderBottom:i<allMembers.length-1?'1pxsolidvar(--dark-border)':'none'}}>
<divstyle={{flex:1}}>
<divstyle={{fontSize:'0.9rem',fontWeight:500}}>{m.profiles?.display_name}</div>
<divstyle={{fontSize:'0.75rem',color:'rgba(255,255,255,0.3)'}}>{m.profiles?.email}</div>
</div>
<spanclassName={`badge${m.status==='approved'?'badge-green':m.status==='rejected'?'badge-red':'badge-grey'}`}>{m.status}</span>
{m.status==='approved'&&(
<EntryFeeTogglemember={m}supabase={supabase}onUpdate={loadTournamentData}/>
)}
</div>
))}
{allMembers.length===0&&<divstyle={{padding:'2rem',textAlign:'center',color:'rgba(255,255,255,0.3)',fontSize:'0.85rem'}}>Nomembersyet</div>}
</div>
</div>
</div>
)}

{/*Matches*/}
{tab==='matches'&&(
<MatchManagermatches={matches}tournamentId={selectedTournament}supabase={supabase}onUpdate={loadTournamentData}/>
)}

{/*Results*/}
{tab==='results'&&(
<ResultsEntrymatches={matches}onSave={saveResult}onLock={lockResult}onEdit={lockResult}onGoLive={goLive}onUpdateLive={updateLiveScore}onEndLive={endLive}/>
)}
</div>
</div>
)
}

functionTournamentSetup({tournament,onSave,onCreate,supabase}:any){
const[form,setForm]=useState(tournament?{...tournament}:{})
const[saving,setSaving]=useState(false)
const[saved,setSaved]=useState(false)
const[creating,setCreating]=useState(false)
const[newName,setNewName]=useState('')
const[newDesc,setNewDesc]=useState('')
const[newFee,setNewFee]=useState('0')

asyncfunctionsaveSettings(){
setSaving(true)
awaitsupabase.from('tournaments').update({...form,updated_at:newDate().toISOString()}).eq('id',tournament.id)
setSaved(true);setTimeout(()=>setSaved(false),2000);onSave();setSaving(false)
}

asyncfunctioncreateTournament(){
if(!newName.trim())return
setCreating(true)
awaitsupabase.from('tournaments').insert({name:newName,description:newDesc,entry_fee:Number(newFee)||0})
setNewName('');setNewDesc('');setNewFee('0');onCreate();setCreating(false)
}

constfield=(label:string,key:string,type='number')=>(
<divkey={key}>
<labelclassName="label">{label}</label>
<inputtype={type}className="input"value={form[key]}onChange={e=>setForm({...form,[key]:type==='number'?Number(e.target.value):e.target.value})}/>
</div>
)

return(
<divstyle={{display:'flex',flexDirection:'column',gap:'1.5rem'}}>
{/*Createnew*/}
<divclassName="card"style={{padding:'1.5rem'}}>
<h3style={{fontFamily:'var(--font-display)',fontSize:'1rem',letterSpacing:'0.08em',marginBottom:'1rem',color:'rgba(255,255,255,0.5)'}}>CREATENEWTOURNAMENT</h3>
<divstyle={{display:'grid',gap:'0.75rem'}}>
<div><labelclassName="label">Tournamentname</label><inputtype="text"className="input"placeholder="e.g.WorkCrewCup"value={newName}onChange={e=>setNewName(e.target.value)}/></div>
<div><labelclassName="label">Description(optional)</label><inputtype="text"className="input"placeholder="Briefdescription..."value={newDesc}onChange={e=>setNewDesc(e.target.value)}/></div>
<div><labelclassName="label">Entryfee(AUD)</label><inputtype="number"className="input"value={newFee}onChange={e=>setNewFee(e.target.value)}/></div>
<buttononClick={createTournament}disabled={creating||!newName.trim()}className="btnbtn-gold"><Plussize={14}/>{creating?'Creating...':'Createtournament'}</button>
</div>
</div>

{/*Pointsconfig*/}
{tournament&&(
<divclassName="card"style={{padding:'1.5rem'}}>
<h3style={{fontFamily:'var(--font-display)',fontSize:'1rem',letterSpacing:'0.08em',marginBottom:'1rem',color:'rgba(255,255,255,0.5)'}}>POINTSCONFIG—{tournament.name.toUpperCase()}</h3>
<divstyle={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(180px,1fr))',gap:'0.75rem'}}>
{field('Correctwinner','pts_winner')}
{field('Correctgoaldiff','pts_goal_diff')}
{field('Exactscore','pts_exact_score')}
{field('Bigmarginbonus','pts_big_margin_bonus')}
{field('Bigmarginthreshold(goals)','big_margin_threshold')}
{field('Qualifyingteams(perteam)','pts_qualify')}
{field('Tournamentwinner','pts_tournament_winner')}
{field('2ndplace','pts_second_place')}
{field('3rdplace','pts_third_place')}
{field('Topscorer','pts_top_scorer')}
</div>
<h4style={{fontFamily:'var(--font-display)',fontSize:'0.9rem',letterSpacing:'0.06em',margin:'1.25rem00.75rem',color:'rgba(255,255,255,0.4)'}}>PHASEMULTIPLIERS</h4>
<divstyle={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(150px,1fr))',gap:'0.75rem'}}>
{field('Groupstage','multiplier_group')}
{field('Roundof32','multiplier_r32')}
{field('Roundof16','multiplier_r16')}
{field('Quarter-finals','multiplier_qf')}
{field('Semi-finals','multiplier_sf')}
{field('Final','multiplier_final')}
</div>
<h4style={{fontFamily:'var(--font-display)',fontSize:'0.9rem',letterSpacing:'0.06em',margin:'1.25rem00.75rem',color:'rgba(255,255,255,0.4)'}}>PRIZEPOOLSPLIT</h4>
<pstyle={{fontSize:'0.78rem',color:'rgba(255,255,255,0.3)',marginBottom:'0.75rem'}}>
Setthe%eachplacereceives.Musttotal100%.Prizepool=entryfee×approvedmembers.
</p>
<divstyle={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'0.75rem',marginBottom:'0.5rem'}}>
<div>
<labelclassName="label">🥇1stplace%</label>
<inputtype="number"className="input"min={0}max={100}value={form.prize_split_1st??60}
onChange={e=>setForm({...form,prize_split_1st:Number(e.target.value)})}/>
</div>
<div>
<labelclassName="label">🥈2ndplace%</label>
<inputtype="number"className="input"min={0}max={100}value={form.prize_split_2nd??30}
onChange={e=>setForm({...form,prize_split_2nd:Number(e.target.value)})}/>
</div>
<div>
<labelclassName="label">🥉3rdplace%</label>
<inputtype="number"className="input"min={0}max={100}value={form.prize_split_3rd??10}
onChange={e=>setForm({...form,prize_split_3rd:Number(e.target.value)})}/>
</div>
</div>
{(()=>{
consttotal=(Number(form.prize_split_1st)||0)+(Number(form.prize_split_2nd)||0)+(Number(form.prize_split_3rd)||0)
return(
<divstyle={{fontSize:'0.78rem',marginBottom:'0.5rem',color:total===100?'#4ade80':'#f87171',fontWeight:600}}>
Total:{total}%{total===100?'✔Good':`—mustequal100%`}
</div>
)
})()}
<buttononClick={saveSettings}disabled={saving}className="btnbtn-primary"style={{marginTop:'1.25rem'}}>
{saved?'✔Saved!':saving?'Saving...':'Savesettings'}
</button>
</div>
)}
</div>
)
}

functionEntryFeeToggle({member,supabase,onUpdate}:any){
const{t}=useLang()
const[paid,setPaid]=useState(member.entry_fee_paid)
asyncfunctiontoggle(){
constnext=!paid
awaitsupabase.from('tournament_members').update({entry_fee_paid:next}).eq('id',member.id)
setPaid(next);onUpdate()
}
return(
<buttononClick={toggle}className={`badge${paid?'badge-green':'badge-grey'}`}style={{cursor:'pointer',border:'none',background:paid?'rgba(34,197,94,0.15)':'rgba(255,255,255,0.06)'}}>
{paid?'$Paid':'$Unpaid'}
</button>
)
}

constFIFA2026_MATCHES=[
{home_team:'Mexico',away_team:'SouthAfrica',kickoff_at:'2026-06-11T19:00:00Z',round:'group',group_name:'GroupA',venue:'MexicoCity'},
{home_team:'SouthKorea',away_team:'Czechia',kickoff_at:'2026-06-12T02:00:00Z',round:'group',group_name:'GroupA',venue:'Guadalajara'},
{home_team:'Czechia',away_team:'SouthAfrica',kickoff_at:'2026-06-18T16:00:00Z',round:'group',group_name:'GroupA',venue:'Atlanta'},
{home_team:'Mexico',away_team:'SouthKorea',kickoff_at:'2026-06-19T03:00:00Z',round:'group',group_name:'GroupA',venue:'Guadalajara'},
{home_team:'Czechia',away_team:'Mexico',kickoff_at:'2026-06-25T01:00:00Z',round:'group',group_name:'GroupA',venue:'MexicoCity'},
{home_team:'SouthAfrica',away_team:'SouthKorea',kickoff_at:'2026-06-25T01:00:00Z',round:'group',group_name:'GroupA',venue:'Guadalajara'},
{home_team:'Canada',away_team:'BosniaandHerzegovina',kickoff_at:'2026-06-12T19:00:00Z',round:'group',group_name:'GroupB',venue:'Toronto'},
{home_team:'Qatar',away_team:'Switzerland',kickoff_at:'2026-06-13T19:00:00Z',round:'group',group_name:'GroupB',venue:'SantaClara'},
{home_team:'Switzerland',away_team:'BosniaandHerzegovina',kickoff_at:'2026-06-18T19:00:00Z',round:'group',group_name:'GroupB',venue:'LosAngeles'},
{home_team:'Canada',away_team:'Qatar',kickoff_at:'2026-06-18T22:00:00Z',round:'group',group_name:'GroupB',venue:'Vancouver'},
{home_team:'Switzerland',away_team:'Canada',kickoff_at:'2026-06-24T19:00:00Z',round:'group',group_name:'GroupB',venue:'Vancouver'},
{home_team:'BosniaandHerzegovina',away_team:'Qatar',kickoff_at:'2026-06-24T19:00:00Z',round:'group',group_name:'GroupB',venue:'Seattle'},
{home_team:'Brazil',away_team:'Morocco',kickoff_at:'2026-06-13T22:00:00Z',round:'group',group_name:'GroupC',venue:'EastRutherford'},
{home_team:'Haiti',away_team:'Scotland',kickoff_at:'2026-06-14T01:00:00Z',round:'group',group_name:'GroupC',venue:'Foxborough'},
{home_team:'Scotland',away_team:'Morocco',kickoff_at:'2026-06-19T22:00:00Z',round:'group',group_name:'GroupC',venue:'Foxborough'},
{home_team:'Brazil',away_team:'Haiti',kickoff_at:'2026-06-20T01:00:00Z',round:'group',group_name:'GroupC',venue:'Philadelphia'},
{home_team:'Scotland',away_team:'Brazil',kickoff_at:'2026-06-24T22:00:00Z',round:'group',group_name:'GroupC',venue:'Miami'},
{home_team:'Morocco',away_team:'Haiti',kickoff_at:'2026-06-24T22:00:00Z',round:'group',group_name:'GroupC',venue:'Atlanta'},
{home_team:'USA',away_team:'Paraguay',kickoff_at:'2026-06-13T01:00:00Z',round:'group',group_name:'GroupD',venue:'LosAngeles'},
{home_team:'Australia',away_team:'Turkey',kickoff_at:'2026-06-14T04:00:00Z',round:'group',group_name:'GroupD',venue:'Vancouver'},
{home_team:'USA',away_team:'Australia',kickoff_at:'2026-06-19T19:00:00Z',round:'group',group_name:'GroupD',venue:'Seattle'},
{home_team:'Turkey',away_team:'Paraguay',kickoff_at:'2026-06-20T04:00:00Z',round:'group',group_name:'GroupD',venue:'SantaClara'},
{home_team:'Turkey',away_team:'USA',kickoff_at:'2026-06-25T02:00:00Z',round:'group',group_name:'GroupD',venue:'LosAngeles'},
{home_team:'Paraguay',away_team:'Australia',kickoff_at:'2026-06-25T02:00:00Z',round:'group',group_name:'GroupD',venue:'SantaClara'},
{home_team:'Germany',away_team:'Curacao',kickoff_at:'2026-06-14T17:00:00Z',round:'group',group_name:'GroupE',venue:'Houston'},
{home_team:'IvoryCoast',away_team:'Ecuador',kickoff_at:'2026-06-14T23:00:00Z',round:'group',group_name:'GroupE',venue:'Philadelphia'},
{home_team:'Germany',away_team:'IvoryCoast',kickoff_at:'2026-06-20T20:00:00Z',round:'group',group_name:'GroupE',venue:'Toronto'},
{home_team:'Ecuador',away_team:'Curacao',kickoff_at:'2026-06-21T00:00:00Z',round:'group',group_name:'GroupE',venue:'KansasCity'},
{home_team:'Ecuador',away_team:'Germany',kickoff_at:'2026-06-25T20:00:00Z',round:'group',group_name:'GroupE',venue:'EastRutherford'},
{home_team:'Curacao',away_team:'IvoryCoast',kickoff_at:'2026-06-25T20:00:00Z',round:'group',group_name:'GroupE',venue:'Philadelphia'},
{home_team:'Netherlands',away_team:'Japan',kickoff_at:'2026-06-14T20:00:00Z',round:'group',group_name:'GroupF',venue:'Arlington'},
{home_team:'Sweden',away_team:'Tunisia',kickoff_at:'2026-06-15T02:00:00Z',round:'group',group_name:'GroupF',venue:'Guadalajara'},
{home_team:'Netherlands',away_team:'Sweden',kickoff_at:'2026-06-20T17:00:00Z',round:'group',group_name:'GroupF',venue:'Houston'},
{home_team:'Tunisia',away_team:'Japan',kickoff_at:'2026-06-21T04:00:00Z',round:'group',group_name:'GroupF',venue:'Guadalajara'},
{home_team:'Japan',away_team:'Sweden',kickoff_at:'2026-06-25T23:00:00Z',round:'group',group_name:'GroupF',venue:'Dallas'},
{home_team:'Tunisia',away_team:'Netherlands',kickoff_at:'2026-06-25T23:00:00Z',round:'group',group_name:'GroupF',venue:'KansasCity'},
{home_team:'Belgium',away_team:'Egypt',kickoff_at:'2026-06-15T22:00:00Z',round:'group',group_name:'GroupG',venue:'Seattle'},
{home_team:'Iran',away_team:'NewZealand',kickoff_at:'2026-06-16T04:00:00Z',round:'group',group_name:'GroupG',venue:'LosAngeles'},
{home_team:'Belgium',away_team:'Iran',kickoff_at:'2026-06-21T19:00:00Z',round:'group',group_name:'GroupG',venue:'LosAngeles'},
{home_team:'NewZealand',away_team:'Egypt',kickoff_at:'2026-06-22T01:00:00Z',round:'group',group_name:'GroupG',venue:'Vancouver'},
{home_team:'NewZealand',away_team:'Belgium',kickoff_at:'2026-06-26T20:00:00Z',round:'group',group_name:'GroupG',venue:'Seattle'},
{home_team:'Egypt',away_team:'Iran',kickoff_at:'2026-06-26T20:00:00Z',round:'group',group_name:'GroupG',venue:'Vancouver'},
{home_team:'Spain',away_team:'CapeVerde',kickoff_at:'2026-06-15T17:00:00Z',round:'group',group_name:'GroupH',venue:'Atlanta'},
{home_team:'SaudiArabia',away_team:'Uruguay',kickoff_at:'2026-06-15T22:00:00Z',round:'group',group_name:'GroupH',venue:'Miami'},
{home_team:'Spain',away_team:'SaudiArabia',kickoff_at:'2026-06-21T16:00:00Z',round:'group',group_name:'GroupH',venue:'Atlanta'},
{home_team:'Uruguay',away_team:'CapeVerde',kickoff_at:'2026-06-21T22:00:00Z',round:'group',group_name:'GroupH',venue:'Miami'},
{home_team:'CapeVerde',away_team:'SaudiArabia',kickoff_at:'2026-06-26T00:00:00Z',round:'group',group_name:'GroupH',venue:'Houston'},
{home_team:'Uruguay',away_team:'Spain',kickoff_at:'2026-06-27T00:00:00Z',round:'group',group_name:'GroupH',venue:'Guadalajara'},
{home_team:'France',away_team:'Senegal',kickoff_at:'2026-06-16T19:00:00Z',round:'group',group_name:'GroupI',venue:'EastRutherford'},
{home_team:'Iraq',away_team:'Norway',kickoff_at:'2026-06-16T22:00:00Z',round:'group',group_name:'GroupI',venue:'Foxborough'},
{home_team:'France',away_team:'Iraq',kickoff_at:'2026-06-22T21:00:00Z',round:'group',group_name:'GroupI',venue:'Philadelphia'},
{home_team:'Norway',away_team:'Senegal',kickoff_at:'2026-06-23T00:00:00Z',round:'group',group_name:'GroupI',venue:'EastRutherford'},
{home_team:'Norway',away_team:'France',kickoff_at:'2026-06-27T19:00:00Z',round:'group',group_name:'GroupI',venue:'Foxborough'},
{home_team:'Senegal',away_team:'Iraq',kickoff_at:'2026-06-27T19:00:00Z',round:'group',group_name:'GroupI',venue:'Toronto'},
{home_team:'Argentina',away_team:'Algeria',kickoff_at:'2026-06-17T01:00:00Z',round:'group',group_name:'GroupJ',venue:'KansasCity'},
{home_team:'Austria',away_team:'Jordan',kickoff_at:'2026-06-17T04:00:00Z',round:'group',group_name:'GroupJ',venue:'SantaClara'},
{home_team:'Argentina',away_team:'Austria',kickoff_at:'2026-06-22T17:00:00Z',round:'group',group_name:'GroupJ',venue:'Dallas'},
{home_team:'Jordan',away_team:'Algeria',kickoff_at:'2026-06-23T03:00:00Z',round:'group',group_name:'GroupJ',venue:'SantaClara'},
{home_team:'Algeria',away_team:'Austria',kickoff_at:'2026-06-27T23:00:00Z',round:'group',group_name:'GroupJ',venue:'KansasCity'},
{home_team:'Jordan',away_team:'Argentina',kickoff_at:'2026-06-28T02:00:00Z',round:'group',group_name:'GroupJ',venue:'Miami'},
{home_team:'Portugal',away_team:'DRCongo',kickoff_at:'2026-06-17T17:00:00Z',round:'group',group_name:'GroupK',venue:'Houston'},
{home_team:'Uzbekistan',away_team:'Colombia',kickoff_at:'2026-06-18T02:00:00Z',round:'group',group_name:'GroupK',venue:'MexicoCity'},
{home_team:'Portugal',away_team:'Uzbekistan',kickoff_at:'2026-06-23T17:00:00Z',round:'group',group_name:'GroupK',venue:'Houston'},
{home_team:'Colombia',away_team:'DRCongo',kickoff_at:'2026-06-24T02:00:00Z',round:'group',group_name:'GroupK',venue:'Guadalajara'},
{home_team:'Colombia',away_team:'Portugal',kickoff_at:'2026-06-28T19:00:00Z',round:'group',group_name:'GroupK',venue:'Dallas'},
{home_team:'DRCongo',away_team:'Uzbekistan',kickoff_at:'2026-06-28T22:00:00Z',round:'group',group_name:'GroupK',venue:'Seattle'},
{home_team:'England',away_team:'Croatia',kickoff_at:'2026-06-17T20:00:00Z',round:'group',group_name:'GroupL',venue:'Dallas'},
{home_team:'Ghana',away_team:'Panama',kickoff_at:'2026-06-17T23:00:00Z',round:'group',group_name:'GroupL',venue:'Toronto'},
{home_team:'England',away_team:'Ghana',kickoff_at:'2026-06-23T20:00:00Z',round:'group',group_name:'GroupL',venue:'Foxborough'},
{home_team:'Panama',away_team:'Croatia',kickoff_at:'2026-06-23T23:00:00Z',round:'group',group_name:'GroupL',venue:'Toronto'},
{home_team:'Croatia',away_team:'Ghana',kickoff_at:'2026-06-28T23:00:00Z',round:'group',group_name:'GroupL',venue:'Boston'},
{home_team:'Panama',away_team:'England',kickoff_at:'2026-06-29T02:00:00Z',round:'group',group_name:'GroupL',venue:'Miami'},
]

functionMatchManager({matches,tournamentId,supabase,onUpdate}:any){
constemptyMatch={home_team:'',away_team:'',kickoff_at:'',round:'group',group_name:'',venue:'',tournament_id:tournamentId}
const[form,setForm]=useState(emptyMatch)
const[saving,setSaving]=useState(false)
const[importing,setImporting]=useState(false)
const[importDone,setImportDone]=useState(false)

asyncfunctionimportFIFA2026(){
if(!confirm('Thiswilladdall72FIFAWorldCup2026groupstagematches.Continue?'))return
setImporting(true)
consttoInsert=FIFA2026_MATCHES.map(m=>({...m,tournament_id:tournamentId}))
for(leti=0;i<toInsert.length;i+=20){
awaitsupabase.from('matches').insert(toInsert.slice(i,i+20))
}
setImportDone(true)
setImporting(false)
onUpdate()
}

asyncfunctionaddMatch(){
if(!form.home_team||!form.away_team||!form.kickoff_at)return
setSaving(true)
awaitsupabase.from('matches').insert(form)
setForm(emptyMatch);onUpdate();setSaving(false)
}

asyncfunctiondeleteMatch(id:string){
if(!confirm('Deletethismatch?'))return
awaitsupabase.from('matches').delete().eq('id',id)
onUpdate()
}

constrounds=[
{value:'group',label:'Groupstage'},{value:'r32',label:'Roundof32'},
{value:'r16',label:'Roundof16'},{value:'qf',label:'Quarter-finals'},
{value:'sf',label:'Semi-finals'},{value:'third_place',label:'3rdPlace'},{value:'final',label:'Final'}
]

return(
<divstyle={{display:'flex',flexDirection:'column',gap:'1.5rem'}}>
<divclassName="card"style={{padding:'1.5rem',background:'rgba(251,191,36,0.04)',border:'1pxsolidrgba(251,191,36,0.15)'}}>
<h3style={{fontFamily:'var(--font-display)',fontSize:'1rem',letterSpacing:'0.08em',marginBottom:'0.5rem',color:'var(--gold)'}}>🌍FIFAWORLDCUP2026—AUTOIMPORT</h3>
<pstyle={{fontSize:'0.82rem',color:'rgba(255,255,255,0.4)',marginBottom:'1rem'}}>Automaticallyaddall72groupstagematcheswithcorrecttimes(storedinUTC).Timeswilldisplayineachuser'slocaltimezone.</p>
<buttononClick={importFIFA2026}disabled={importing||importDone}className="btnbtn-gold">
{importDone?'✔All72matchesimported!':importing?'Importing...':'⚡ImportallFIFA2026groupstagematches'}
</button>
</div>

<divclassName="card"style={{padding:'1.5rem'}}>
<h3style={{fontFamily:'var(--font-display)',fontSize:'1rem',letterSpacing:'0.08em',marginBottom:'1rem',color:'rgba(255,255,255,0.5)'}}>ADDMATCHMANUALLY</h3>
<divstyle={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(180px,1fr))',gap:'0.75rem'}}>
<div><labelclassName="label">Hometeam</label><inputtype="text"className="input"placeholder="e.g.Brazil"value={form.home_team}onChange={e=>setForm({...form,home_team:e.target.value})}/></div>
<div><labelclassName="label">Awayteam</label><inputtype="text"className="input"placeholder="e.g.Argentina"value={form.away_team}onChange={e=>setForm({...form,away_team:e.target.value})}/></div>
<div><labelclassName="label">Kickoff(localtime)</label><inputtype="datetime-local"className="input"value={form.kickoff_at}onChange={e=>setForm({...form,kickoff_at:e.target.value})}/></div>
<div><labelclassName="label">Round</label>
<selectclassName="input"value={form.round}onChange={e=>setForm({...form,round:e.target.value})}>
{rounds.map(r=><optionkey={r.value}value={r.value}>{r.label}</option>)}
</select>
</div>
<div><labelclassName="label">Group(optional)</label><inputtype="text"className="input"placeholder="e.g.GroupA"value={form.group_name}onChange={e=>setForm({...form,group_name:e.target.value})}/></div>
<div><labelclassName="label">Venue(optional)</label><inputtype="text"className="input"placeholder="e.g.SoFiStadium"value={form.venue}onChange={e=>setForm({...form,venue:e.target.value})}/></div>
</div>
<buttononClick={addMatch}disabled={saving}className="btnbtn-primary"style={{marginTop:'1rem'}}>
<Plussize={14}/>{saving?'Adding...':'Addmatch'}
</button>
</div>

<div>
<h3style={{fontFamily:'var(--font-display)',fontSize:'1rem',letterSpacing:'0.08em',marginBottom:'0.75rem',color:'rgba(255,255,255,0.5)'}}>MATCHES({matches.length})</h3>
<divclassName="card"style={{overflow:'hidden'}}>
{matches.length===0&&<divstyle={{padding:'2rem',textAlign:'center',color:'rgba(255,255,255,0.3)',fontSize:'0.85rem'}}>Nomatchesaddedyet</div>}
{matches.map((m:any,i:number)=>(
<divkey={m.id}style={{display:'flex',alignItems:'center',gap:'0.75rem',padding:'0.875rem1.25rem',borderBottom:i<matches.length-1?'1pxsolidvar(--dark-border)':'none'}}>
<divstyle={{flex:1}}>
<spanstyle={{fontWeight:500,fontSize:'0.9rem'}}>{m.home_team}vs{m.away_team}</span>
<spanstyle={{fontSize:'0.75rem',color:'rgba(255,255,255,0.3)',marginLeft:'0.5rem'}}>{m.round}·{format(newDate(m.kickoff_at),'dMMMHH:mm')}</span>
{m.group_name&&<spanclassName="badgebadge-grey"style={{marginLeft:'0.5rem'}}>{m.group_name}</span>}
</div>
<spanclassName={`badge${m.status==='completed'?'badge-green':m.status==='live'?'badge-gold':'badge-grey'}`}>{m.status}</span>
{m.status==='completed'&&<spanstyle={{fontSize:'0.85rem',fontFamily:'var(--font-display)'}}>{m.home_score}–{m.away_score}</span>}
<buttononClick={()=>deleteMatch(m.id)}style={{background:'none',border:'none',color:'rgba(239,68,68,0.5)',cursor:'pointer',padding:'0.25rem'}}><Xsize={14}/></button>
</div>
))}
</div>
</div>
</div>
)
}

functionResultsEntry({matches,onSave,onLock,onEdit,onGoLive,onUpdateLive,onEndLive}:any){
const[scores,setScores]=useState<Record<string,{home:string,away:string}>>({})
const[editing,setEditing]=useState<string|null>(null)
const[saving,setSaving]=useState<string|null>(null)

functionsetScore(matchId:string,key:'home'|'away',val:string){
setScores(prev=>({...prev,[matchId]:{...prev[matchId],[key]:val}}))
}

functionstartEdit(m:any){
setEditing(m.id)
setScores(prev=>({...prev,[m.id]:{home:String(m.home_score),away:String(m.away_score)}}))
}

asyncfunctionhandleSave(matchId:string){
consts=scores[matchId]
if(!s||s.home===''||s.away==='')return
setSaving(matchId)
awaitonSave(matchId,Number(s.home),Number(s.away))
setSaving(null)
}

asyncfunctionhandleLock(matchId:string){
consts=scores[matchId]
if(!s||s.home===''||s.away==='')return
if(!confirm('Lockthisresult?Pointswillbecalculatedandplayerswillseethescore.'))return
setSaving(matchId)
awaitonLock(matchId,Number(s.home),Number(s.away))
setSaving(null)
}

constlive=matches.filter((m:any)=>m.status==='live')
constpending=matches.filter((m:any)=>m.status!=='completed'&&m.status!=='live')
constcompleted=matches.filter((m:any)=>m.status==='completed')

return(
<divstyle={{display:'flex',flexDirection:'column',gap:'1.5rem'}}>
{live.length>0&&(
<divstyle={{marginBottom:'1.5rem'}}>
<h3style={{fontFamily:'var(--font-display)',fontSize:'1rem',letterSpacing:'0.08em',marginBottom:'0.75rem',color:'#f87171'}}>🔴LIVENOW</h3>
<divstyle={{display:'flex',flexDirection:'column',gap:'0.6rem'}}>
{live.map((m:any)=>{
consts=scores[m.id]!==undefined?scores[m.id]:{home:String(m.home_score??0),away:String(m.away_score??0)}
constisSaving=saving===m.id
return(
<divkey={m.id}className="card"style={{padding:'1rem1.25rem',border:'1pxsolidrgba(248,113,113,0.3)',display:'flex',alignItems:'center',gap:'1rem',flexWrap:'wrap'}}>
<divstyle={{flex:1}}>
<divstyle={{display:'flex',alignItems:'center',gap:'0.5rem',marginBottom:'0.2rem'}}>
<spanstyle={{width:8,height:8,borderRadius:'50%',background:'#f87171',display:'inline-block'}}/>
<spanstyle={{fontSize:'0.75rem',color:'#f87171',fontWeight:600}}>LIVE</span>
</div>
<spanstyle={{fontWeight:600}}>{m.home_team}vs{m.away_team}</span>
<spanstyle={{fontFamily:'var(--font-display)',fontSize:'1.4rem',marginLeft:'1rem',color:'#f87171'}}>{m.home_score??0}–{m.away_score??0}</span>
</div>
<divstyle={{display:'flex',alignItems:'center',gap:'0.5rem',flexWrap:'wrap'}}>
<inputtype="number"className="score-input"min={0}max={99}value={s.home}onChange={e=>setScore(m.id,'home',e.target.value)}/>
<spanstyle={{color:'rgba(255,255,255,0.3)',fontFamily:'var(--font-display)',fontSize:'1.2rem'}}>–</span>
<inputtype="number"className="score-input"min={0}max={99}value={s.away}onChange={e=>setScore(m.id,'away',e.target.value)}/>
<buttonclassName="btnbtn-ghost"style={{padding:'0.5rem0.8rem',fontSize:'0.8rem',color:'#f87171'}}disabled={isSaving}onClick={async()=>{setSaving(m.id);awaitonUpdateLive(m.id,Number(s.home),Number(s.away));setSaving(null)}}>
{isSaving?'...':'⚡UpdateScore'}
</button>
<buttonclassName="btnbtn-primary"style={{padding:'0.5rem1rem',fontSize:'0.8rem',background:'rgba(34,197,94,0.2)',borderColor:'#4ade80',color:'#4ade80'}}disabled={isSaving}onClick={async()=>{if(confirm('Endmatchandlockfinalresult?')){setSaving(m.id);awaitonEndLive(m.id,Number(s.home),Number(s.away));setSaving(null)}}}>
✔FullTime
</button>
</div>
</div>
)
})}
</div>
</div>
)}

<div>
<h3style={{fontFamily:'var(--font-display)',fontSize:'1rem',letterSpacing:'0.08em',marginBottom:'0.5rem',color:'rgba(255,255,255,0.5)'}}>PENDINGRESULTS</h3>
<pstyle={{fontSize:'0.8rem',color:'rgba(255,255,255,0.3)',marginBottom:'0.75rem'}}>
Enterthescoreandclick<strongstyle={{color:'rgba(255,255,255,0.5)'}}>Save</strong>tostoreitprivately,or<strongstyle={{color:'#4ade80'}}>LockResult</strong>topublishitandcalculatepoints.
</p>
{pending.length===0&&(
<divclassName="card"style={{padding:'2.5rem',textAlign:'center',color:'rgba(255,255,255,0.3)',fontSize:'0.85rem'}}>
Allmatchresultshavebeenlocked—greatwork!
</div>
)}
<divstyle={{display:'flex',flexDirection:'column',gap:'0.6rem'}}>
{pending.map((m:any)=>{
consts=scores[m.id]||{home:m.home_score!==null?String(m.home_score):'',away:m.away_score!==null?String(m.away_score):''}
constisSaving=saving===m.id
consthasSavedScore=m.home_score!==null&&m.away_score!==null
return(
<divkey={m.id}className="card"style={{padding:'1rem1.25rem',display:'flex',alignItems:'center',gap:'1rem',flexWrap:'wrap'}}>
<divstyle={{flex:1}}>
<spanstyle={{fontWeight:500}}>{m.home_team}vs{m.away_team}</span>
<spanstyle={{fontSize:'0.75rem',color:'rgba(255,255,255,0.3)',marginLeft:'0.5rem'}}>{newDate(m.kickoff_at).toLocaleString(undefined,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hour12:false})}</span>
{hasSavedScore&&<spanclassName="badgebadge-grey"style={{marginLeft:'0.5rem'}}>Draft:{m.home_score}–{m.away_score}</span>}
</div>
<divstyle={{display:'flex',alignItems:'center',gap:'0.5rem',flexWrap:'wrap'}}>
<inputtype="number"className="score-input"min={0}max={99}placeholder="0"value={s.home}onChange={e=>setScore(m.id,'home',e.target.value)}/>
<spanstyle={{color:'rgba(255,255,255,0.3)',fontFamily:'var(--font-display)',fontSize:'1.2rem'}}>–</span>
<inputtype="number"className="score-input"min={0}max={99}placeholder="0"value={s.away}onChange={e=>setScore(m.id,'away',e.target.value)}/>
<buttonclassName="btnbtn-ghost"style={{padding:'0.5rem0.8rem',fontSize:'0.8rem'}}disabled={isSaving||s.home===''||s.away===''}onClick={()=>handleSave(m.id)}>
{isSaving?'...':'Save'}
</button>
<buttonclassName="btnbtn-ghost"style={{padding:'0.5rem0.8rem',fontSize:'0.8rem',color:'#f87171'}}disabled={isSaving}onClick={()=>onGoLive(m.id)}>
🔴GoLive
</button>
<buttonclassName="btnbtn-primary"style={{padding:'0.5rem1rem',fontSize:'0.8rem',background:'rgba(34,197,94,0.2)',borderColor:'#4ade80',color:'#4ade80'}}disabled={isSaving||s.home===''||s.away===''}onClick={()=>handleLock(m.id)}>
🔒LockResult
</button>
</div>
</div>
)
})}
</div>
</div>

{completed.length>0&&(
<div>
<h3style={{fontFamily:'var(--font-display)',fontSize:'1rem',letterSpacing:'0.08em',marginBottom:'0.75rem',color:'rgba(255,255,255,0.5)'}}>LOCKEDRESULTS—CLICKEDITTOCORRECT</h3>
<divstyle={{display:'flex',flexDirection:'column',gap:'0.6rem'}}>
{completed.map((m:any)=>{
consts=scores[m.id]||{home:String(m.home_score),away:String(m.away_score)}
constisEditing=editing===m.id
constisSaving=saving===m.id
return(
<divkey={m.id}className="card"style={{padding:'1rem1.25rem',display:'flex',alignItems:'center',gap:'1rem',flexWrap:'wrap'}}>
<divstyle={{flex:1}}>
<spanstyle={{fontWeight:500}}>{m.home_team}vs{m.away_team}</span>
<spanstyle={{fontSize:'0.75rem',color:'rgba(255,255,255,0.3)',marginLeft:'0.5rem'}}>{newDate(m.kickoff_at).toLocaleString(undefined,{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hour12:false})}</span>
</div>
{isEditing?(
<divstyle={{display:'flex',alignItems:'center',gap:'0.5rem'}}>
<inputtype="number"className="score-input"min={0}max={99}value={s.home}onChange={e=>setScore(m.id,'home',e.target.value)}/>
<spanstyle={{color:'rgba(255,255,255,0.3)',fontFamily:'var(--font-display)',fontSize:'1.2rem'}}>–</span>
<inputtype="number"className="score-input"min={0}max={99}value={s.away}onChange={e=>setScore(m.id,'away',e.target.value)}/>
<buttonclassName="btnbtn-primary"style={{padding:'0.5rem1rem',fontSize:'0.8rem'}}disabled={isSaving}onClick={async()=>{setSaving(m.id);awaitonEdit(m.id,Number(s.home),Number(s.away));setSaving(null);setEditing(null)}}>
{isSaving?'...':'Save&Lock'}
</button>
<buttonclassName="btnbtn-ghost"style={{padding:'0.5rem1rem',fontSize:'0.8rem'}}onClick={()=>setEditing(null)}>
Cancel
</button>
</div>
):(
<divstyle={{display:'flex',alignItems:'center',gap:'0.75rem'}}>
<spanstyle={{fontFamily:'var(--font-display)',fontSize:'1.4rem'}}>{m.home_score}–{m.away_score}</span>
<spanclassName="badgebadge-green">locked</span>
<buttonclassName="btnbtn-ghost"style={{padding:'0.4rem0.8rem',fontSize:'0.8rem'}}onClick={()=>startEdit(m)}>
Edit
</button>
</div>
)}
</div>
)
})}
</div>
</div>
)}
</div>
)
}

